
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./volumes/uptime-kuma:/app/data
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
    restart: always
    networks:
      private_network:
        ipv4_address: 172.19.0.11
  volumes:
    uptime-kuma:    