  
#---------------------------------------------------------------------#
#     SYNCTHING UI                                                    #
#---------------------------------------------------------------------# 
  
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./volumes/syncthing/config:/config
      - /media/32GUSB/data1:/data1
      - /media/32GUSB/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      private_network:
        ipv4_address: 172.19.0.35    
    restart: unless-stopped
    labels:
      - homepage.group=MEDIA
      - homepage.name=syncthing
      - homepage.icon=jellyfin.png
      - homepage.href=http://192.168.1.30:8384
      - homepage.description=syncthing backup
