  
#---------------------------------------------------------------------#
#     SONARR UI                                                       #
#---------------------------------------------------------------------# 
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      #modify below paths to your setups folders choices in portainer + pi/linux mounted drives in 'fstab
      - /media/YOUR-USB-DRIVE-PATH/TV:/tv
      - /media/YOUR-USB-DRIVE-PATH/DOWNLOADS:/downloads
    ports:
      - 8989:8989
    networks:
      private_network:
        ipv4_address: 172.19.0.32  
    restart: unless-stopped
