  
#---------------------------------------------------------------------#
#     SONARR UI                                                       #
#---------------------------------------------------------------------# 
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
        #modify below paths to your setups folders choices in portainer + pi/linux or mounted drives in 'fstab
      - /media/YOUR-USB-DRIVE-PATH/TV:/tv
      - /media/YOUR-USB-DRIVE-PATH/DOWNLOADS:/downloads
    ports:
      - 8989:8989
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8989/UI/Dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - homepage.group=MEDIA
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://192.168.1.30:8989
      - homepage.description=tv sonarr  
    networks:
      private_network:
        ipv4_address: 172.19.0.32 # internal address of sonarr
    restart: unless-stopped
