---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

# My own quick template to help setup presto homepage customise as needed

- My  Sites:
    - tempmail:
        href: https://temp-mail.org/
        description: temp mail
    - photoshop:
        href: https://www.photopea.com/
        description: free photoshop
    - sandbox:
        href: https://sandspiel.club/
        desctription: free sandbox game
 
- Presto Media:
    - Sonarr:
        icon: sonarr.svg
        href: http://192.168.1.100 or rpi4 :8989
        widget:
          type: sonarr
          url: http://192.168.1.100 or rpi4 :8989
          key: #apikey here look to respective app settings for it 
          enableQueue: true # optional, defaults to false
    - Radarr:
        icon: radarr.svg
        href: http://192.168.1.100 or rpi4 :7878
        widget:
          type: radarr
          url: http://192.168.1.100 or rpi4 :7878
          key: #apikey here look to respective app settings for it
          enableQueue: true # optional, defaults to false
          

    - Lidarr:
        icon: lidarr.svg
        href: http://192.168.1.100 or rpi4 :8686
        widget:
          type: lidarr
          url: http://192.168.1.100 or rpi4 :8686
          key: #apikey here look to respective app settings for it

    - Jellyfin:
        icon: jellyfin.svg
        href: http://rpi4-nas:8096
        widget:
          type: jellyfin
          url: http://rpi4-nas:8096
          key: #apikey here look to respective app settings for it
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: true # optional, defaults to true

    - Qbittorrent:
        icon: qbittorrent.svg
        href: http://192.168.1.100 or rpi4 :15080
        description: Torrent downloader
        widget:
          type: qbittorrent
          url: http://192.168.1.100 or rpi4 :15080
          username: admin
          password: adminadmin

    - Tautulli:
        icon: tautulli.svg
        href: http://192.168.1.100 or rpi4 :8181
        widget:
          type: tautulli
          url: http://192.168.1.100 or rpi4 :8181
          key: #apikey here look to respective app settings for it
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true

    #- plex:
    #    icon: plex.svg
    #    href: http://192.168.1.100 or rpi4 :32400
    #    widget:
    #      type: plex
    #      url: http://192.168.1.100 or rpi4 :32400
    #      key: apikeyhere # see https://www.plexopedia.com/plex-media-server/general/plex-token/

    #- homarr:
    #    icon: homarr.svg
    #    href: http://192.168.1.100 or rpi4 :7575
    #    widget:
    #      type: homarr
    #      url: http://192.168.1.100 or rpi4 :7575
    #      key: apikeyapikeyapikeyapikeyapikey

    - Jackett:
        icon: jackett.svg
        href: http://192.168.1.100 or rpi4 :9117
        widget:
          type: jackett
          url: http://192.168.1.100 or rpi4 :9117


    - Uptimekuma:
        icon: uptime-kuma.svg
        href: http://rpi4-nas:3001
        widget:
          type: uptimekuma
          url: http://rpi4-nas:3001
          slug: dash

    - Motioneye:
        icon: motioneye.svg
        href: http://192.168.1.100 or rpi4 :8765
        #widget:
          #type: motioneye
          #url: http://192.168.1.100 or rpi4 :8765


- Media Calendar:
    - calendar:
        #icon: google-calendar.svg
        icon: nextcloud-calendar.svg
        widget:
          type: calendar
          firstDayInWeek: sunday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: Europe/London # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Presto Media  # group name where widget exists
              service_name: Sonarr # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
              params: # optional - additional params for the service
                unmonitored: false # optional - defaults to false, used with *arr stack

            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Presto Media  # group name where widget exists
              service_name: Radarr # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
              params: # optional - additional params for the service
                unmonitored: false # optional - defaults to false, used with *arr stack

            - type: lidarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Presto Media  # group name where widget exists
              service_name: Lidarr # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
              params: # optional - additional params for the service
                unmonitored: false # optional - defaults to false, used with *arr stack

- Presto System:
    - PiHole:
        icon: pi-hole.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: http://192.168.1.100 or rpi4 :80/admin
        description: Server 1
        widget:
          type: pihole
          url: http://192.168.1.100 or rpi4 :80
          key: "#apikey here look to respective app settings for it" #
    - Glances:
        icon: glances.svg
        href: http://192.168.1.100 or rpi4 :61208
        description: CPU
        widget:
          type: glances
          url: http://192.168.1.100 or rpi4 :61208
          #username: user # optional if auth enabled in Glances
          #password: pass # optional if auth enabled in Glances
          version: 4 # required only if running glances v4 or higher, defaults to 3
          metric: cpu
          diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
          refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
          pointsLimit: 15 # optional, defaults to 15

    - Glances:
        icon: glances.png
        href: http://rpi4-nas:61208
        description: Top5 Procs
        widget:
          type: glances
          url: http//:192.168.1.100:61208
          version: 4
          metric: process
          refreshInterval: 5000
    - Glances:
        icon: glances.png
        href: http://192.168.1.100 or rpi4 :61208
        description: cpu temp
        widget:
          type: glances
          url: http//:192.168.1.100:61208
          version: 4
          metric: sensor:cpu_thermal 0
          refreshInterval: 5000
    - Glances:
        icon: glances.png
        href: http://192.168.1.100 or rpi4 :61208
        description: INFO
        widget:
          type: glances
          url: http//:192.168.1.100:61208
          version: 4
          metric: info
          refreshInterval: 5000
    #- Glances:
    #    icon: glances.png
    #    href: http://192.168.1.100 or rpi4 :61208
    #    description: NVME
    #    widget:
    #      type: glances
    #      url: http//:192.168.1.100:61208
    #      version: 4
    #      metric: disk:nvme0n1
    #      refreshInterval: 5000
