  
#---------------------------------------------------------------------#
#     OVERSEER UI   for /*arrs                                        #
#---------------------------------------------------------------------#  

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./volumes/overseerr/config:/config
    ports:
      - 5055:5055
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5055"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s    
    labels:
      - homepage.group=MEDIA
      - homepage.name=overseerr
      - homepage.icon=overseerr.png
      - homepage.href=http://192.168.1.30:5055  
      - homepage.description= media grabber 
    networks:
      private_network:
        ipv4_address: 172.19.0.25 # internal address of overseer
    restart: unless-stopped