  
#---------------------------------------------------------------------#
#     OVERSEER UI   for /*arrs                                        #
#---------------------------------------------------------------------#  

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    volumes:
      - ./volumes/overseerr/config:/config
    env_file:
      - ./services/overseerr/overseerr.env    
    ports:
      - 5055:5055
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5055"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s    
    labels:
      - homepage.group=MEDIA
      - homepage.name=overseerr
      - homepage.icon=overseerr.png
      - homepage.href=http://${RASPBERRYPI_HOST_IP}:5055  
      - homepage.description= media grabber 
    networks:
      private_network:
        ipv4_address: 172.19.0.25 # internal address of overseer
    restart: unless-stopped