  
#---------------------------------------------------------------------#
#     OVERSEER UI   for /*arrs                                        #
#---------------------------------------------------------------------#  

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./volumes/overseerr/config:/config
    ports:
      - 5055:5055
    networks:
      private_network:
        ipv4_address: 172.19.0.25  
    restart: unless-stopped