  
#---------------------------------------------------------------------#
#     LIDARR UI                                                       #
#---------------------------------------------------------------------#  
  
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    env_file:
      - ./services/lidarr/lidarr.env    
    volumes:
      - ./volumes/lidarr/config:/config
      #modify below paths to your setups folders choices in portainer + pi/linux mounted drives in 'fstab
      - /media/USB_PLEX_14TB/MUSIC:/music
      - /media/USB_PLEX_14TB/DOWNLOADS:/downloads
    ports:
      - 8686:8686
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8686/UI/Dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  
    labels:
      - homepage.group=MEDIA
      - homepage.name=lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://${RASPBERRYPI_HOST_IP}:8686
      - homepage.description=song manager  
    networks:
      private_network:
        ipv4_address: 172.19.0.24 # internal address of lidarr
