
#---------------------------------------------------------------------#
#     WireGuard UI                                                    #
#---------------------------------------------------------------------#

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    #depends_on:
    #  - wireguard
    depends_on:
      wireguard:
        condition: service_completed_successfully
    restart: always  
    cap_add:
      - NET_ADMIN
    # Use the network of the 'wireguard' service
    # This enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WGUI_SERVER_INTERFACE_ADDRESSES	
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./volumes/wireguard/db:/app/db
      - ./volumes/wireguard/config:/etc/wireguard
      