  
#---------------------------------------------------------------------#
#     PROWLARR UI                                                     #
#---------------------------------------------------------------------#

  prowlarr:
      image: lscr.io/linuxserver/prowlarr:latest
      container_name: prowlarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./volumes/prowlarr/data:/config
      ports:
        - 9696:9696
      restart: unless-stopped
