
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/homarr/config:/app/data/configs
      - ./volumes/homarr/icons:/app/public/icons
    ports:
      - 7575:7575
    labels:
      - homepage.group=NETWORK
      - homepage.name=homarr
      - homepage.icon=homarr.png
      - homepage.href=http://192.168.1.30:7575
      - homepage.description=Server Dashboard
    networks:
      private_network:
        ipv4_address: 172.19.0.21  