  
#---------------------------------------------------------------------#
#    motioneye - A simple,security camera server.                     #
#---------------------------------------------------------------------#
  
  motioneye:
    #image: "ccrisan/motioneye:master-armhf" old ver for old pi's
    image: "ghcr.io/motioneye-project/motioneye:edge" #64bit pi's
    container_name: "motioneye"
    restart: unless-stopped
    ports:
      - 8765:8765 
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/motioneye/etc_motioneye:/etc/motioneye
      - ./volumes/motioneye/var_lib_motioneye:/var/lib/motioneye
    devices:
      - "/dev/video0:/dev/video0"
    networks:
      private_network:
        ipv4_address: 172.19.0.38 # internal address of motioneye #
