
#---------------------------------------------------------------------#
#     Homepage                                                        #
#---------------------------------------------------------------------#

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - ./services/homepage/homepage.env  
    #using sockets so need root- pid disabled
    #  PUID: 1000 # optional, your user id
    #  PGID: 1000 # optional, your group id
    ports:
      - 3000:3000
    volumes:
      - ./volumes/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # optional, for docker integrations runs as root so PUID and PGID not needed if you want to see runing containers
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider http://0.0.0.0:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      private_network:
        ipv4_address: 172.19.0.42 # internal address of homepage
