  
#---------------------------------------------------------------------#
#     JACKETT UI                                                       #
#---------------------------------------------------------------------# 
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - /media/USB_PLEX_14TB/DOWNLOADS:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

    labels:
      - homepage.group=MEDIA
      - homepage.name=jackett
      - homepage.icon=jackett.png
      - homepage.href=http://192.168.1.30:9117      
      - homepage.description= Torrent indexer 
    networks:
      private_network:
        ipv4_address: 172.19.0.22 # internal address of jackett
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'jackett --NoRestart' >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
