  
#---------------------------------------------------------------------#
#     GLANCES                                                         #
#---------------------------------------------------------------------#  
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: always
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
      #- /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro #RHEL?
      - ./volumes/glances/glances.conf:/glances/conf/glances.conf    
      # Mount the entrypoint script and template from the presto root directory.
      - ./.templates/glances/entrypoint.sh:/entrypoint.sh
      - ./.templates/glances/glances.conf.template:/app/glances.conf.template
    entrypoint: ["/entrypoint.sh"]  
    environment:      
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - GLANCES_OPT=-w
      #- GLANCES_OPT=-C /glances/conf/glances.conf -w
      - GLOBAL_REFRESH=2 # Set the global refresh rate for Glances
    
    ports:
      - "61208-61209:61208-61209"
    labels:
      - homepage.group=NETWORK
      - homepage.name=glances
      - homepage.icon=glances.png
      - homepage.href=http://${RASPBERRYPI_HOST_IP}:61208  
      - homepage.description=system info top hub
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:61208"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      private_network:
        ipv4_address: 172.19.0.39 # internal address of glances