  
#---------------------------------------------------------------------#
#     qbittorrent                                                      #
#---------------------------------------------------------------------#  
  
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - WEBUI_PORT=15080
    volumes:
      - ./volumes/qbittorrent/config:/config
      #modify below paths to your setups folders choices in portainer + pi/linux mounted drives in 'fstab
      - /media/YOUR-USB-DRIVE-PATH/DOWNLOADS:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 15080:15080
      - 1080:1080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s     
    restart: unless-stopped
    labels:
      - homepage.group=MEDIA
      - homepage.name=qbittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://192.168.1.30:15080
      - homepage.description= Torrent Downloader
    networks:
      private_network:
        ipv4_address: 172.19.0.29 # internal address of qbittorrent
