  
#---------------------------------------------------------------------#
#     PROWLARR UI                                                     #
#---------------------------------------------------------------------#

  prowlarr:
      image: lscr.io/linuxserver/prowlarr:latest
      container_name: prowlarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./volumes/prowlarr/data:/config
      ports:
        - 9696:9696
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:9696"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 60s        
      labels:
      - homepage.group=MEDIA
      - homepage.name=prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://192.168.1.30:9696
      - homepage.description= T indexer
      networks:
        private_network:
          ipv4_address: 172.19.0.43 # internal address of prowler
      restart: unless-stopped
