  
#---------------------------------------------------------------------#
#     PROWLARR UI                                                     #
#---------------------------------------------------------------------#

  prowlarr:
      image: lscr.io/linuxserver/prowlarr:latest
      container_name: prowlarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./volumes/prowlarr/data:/config
      ports:
        - 9696:9696
      labels:
      - homepage.group=MEDIA
      - homepage.name=prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://192.168.1.51:9696
      - homepage.description= T indexer

      restart: unless-stopped
