  
#---------------------------------------------------------------------#
#     HomeAssistant                                                   #
#---------------------------------------------------------------------#   
  
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: always
    privileged: true
#   network_mode: host
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
    devices:
    - '/dev/ttyUSB0'
    - '/dev/ttyACM0'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volumes/homeassistant/conf:/config
      - ./volumes/homeassistant/addons:/homeassistant/addons
      - ./volumes/homeassistant/conf:/homeassistant/conf
      - ./volumes/homeassistant/userdata:/homeassistant/userdata
    env_file:
      - ./services/homeassistant/homeassistant.env  
    ports:
      - 8123:8123
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8123"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s     
    labels:
      - homepage.group=NETWORK
      - homepage.name=home-assistant
      - homepage.icon=home-assistant.png
      - homepage.href=http://${RASPBERRYPI_HOST_IP}:8123
      - homepage.description=Home Assistant
    networks:
      private_network:
        ipv4_address: 172.19.0.40 # internal address of homeassistant 