  
#---------------------------------------------------------------------#
#     RADARR UI                                                       #
#---------------------------------------------------------------------#  
  
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      #modify below paths to your setups folders choices in portainer + pi/linux mounted drives in 'fstab
      - /media/YOUR-USB-DRIVE-PATH/MOVIES:/movies
      - /media/YOUR-USB-DRIVE-PATH/DOWNLOADS:/downloads
    ports:
      - 7878:7878
    labels:
      - homepage.group=MEDIA
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://192.168.1.30:7878
      - homepage.description=movie radarr    
    networks:
      private_network:
        ipv4_address: 172.19.0.30 # internal address of radarr
    restart: unless-stopped
